name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Buildv
        run: dotnet publish --configuration Release --self-contained false --runtime win-x86 /p:PublishSingleFile=true
      - name: Zip output file
        run: Compress-Archive -Path "./bin/Release/net7.0-windows/win-x86/publish/RH Table Tool.exe" -DestinationPath RH_Table_Tool.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RH Table Tool
          path: RH_Table_Tool.zip
